### ISSUE TITLE
android bugs

### ISSUE THREAD

**Issue by ghost** [spoonconsulting/cordova-plugin-genius-scan#1]
On the android pixel 2 i detected the following bugs:
- when scanning a second page and after setting the quadrangle we sometimes get a black screen, afterward the image is not found.
- after setting the quadrangle when going back to the quadrangle page, the original quadrangle is lost, in this case setting the quadrangle again also does not do a transformation.

These bugs prevent me to use this in production

**Comment by l0stpenguin** [comment]
Hi, @jjdf01 this repo is just a temporary plugin for a project of mine, please use the official one from npm:
[https://www.npmjs.com/package/@thegrizzlylabs/cordova-plugin-genius-scan](https://www.npmjs.com/package/@thegrizzlylabs/cordova-plugin-genius-scan)

**Comment by ghost** [comment]
ah woops, wrong place to post my bad, i was using that one.
